name: Deployment pipeline

on:
    push: 
        paths:
          - 'random-quote-machine/**'
        branches:
          - main

jobs:
      simple_deployment_pipeline:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4 
              with: 
                node-version: '20'        
            - name: Install dependencies
              run:  | 
                cd ./random-quote-machine
                npm install
            - name: Check style
              run: | 
                cd ./random-quote-machine
                npm run lint
            - name: Test
              run: |
                cd ./random-quote-machine
                npm run test
        